### ISSUE TITLE
standardize plotting commands in R

### ISSUE THREAD

**Issue by kcranston** [Reproducible-Science-Curriculum/rr-automation#4]
Duplicate of [this issue in organization](https://github.com/Reproducible-Science-Curriculum/rr-organization1/issues/25). Use either plot or ggplot consistently throughout R lessons

**Comment by fmichonneau** [comment]
Thanks Karen! originally reported here: Reproducible-Science-Curriculum/rr-organization1#25

**Comment by fmichonneau** [comment]
I need more :coffee:

**Comment by fmichonneau** [comment]
the lesson only uses ggplot now

**Comment by kcranston** [comment]
Thanks!
